### ISSUE TITLE
E-mail alert

### ISSUE THREAD

**Issue by fredrikjahr** [jreinke/magento-stock-movements#19]
Hi,
Is it possible to send an e-mail alert for any stock movement that is made and include either the entire stock movement table in the email or the latest row in the table?

Thanks for a great module!

**Comment by jreinke** [comment]
Hi,

Sorry for the late reply but I think you should use the default event/observer pattern of Magento for this purpose. I have added some useful info to catch the event easily. You can listen to `stock_movement_save_after` for example.
