### ISSUE TITLE
how does one fully un-install the extension?

### ISSUE THREAD

**Issue by seansan** [jreinke/magento-stock-movements#25]
how does one fully un-install the extension?

**Comment by sprankhub** [comment]
1. Remove all extension files:

        rm -r app/code/community/Bubble/StockMovements/
        rm app/etc/modules/Bubble_StockMovements.xml
        rm app/locale/en_US/Bubble_StockMovements.csv
        rm app/locale/fr_FR/Bubble_StockMovements.csv
        rm app/locale/pt_BR/Bubble_StockMovements.csv

2. Cleanup database:

        DROP TABLE `bubble_stock_movement`;
        DELETE FROM `core_resource` WHERE `code` = 'bubble_stockmovements_setup';

**Comment by seansan** [comment]
thx! maybe add -rf to avoid confirmations

**Comment by sprankhub** [comment]
Yeah, you can do that as well. Please close this issue if my answer solves it.

**Comment by seansan** [comment]
https://github.com/jreinke/magento-stock-movements/pull/27
